<?php
/**
 * Created by PhpStorm.
 * User: Jackie
 * Date: 5/23/2018
 * Time: 9:28 AM
 */

namespace Sm\Learn\Block;


class Main extends \Magento\Framework\View\Element\Template
{
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    public function getTest() {
        return 'đasad';
    }


}