<?php
/**
 * Created by PhpStorm.
 * User: Jackie
 * Date: 5/23/2018
 * Time: 9:36 AM
 */

namespace Sm\Learn\Block;


class ValidationMessages extends \Magento\Framework\View\Element\Messages
{
    protected function _prepareLayout()
    {
        $this->messageManager->addNotice('aaaaaaaaaaaaaa');
        $this->addMessages($this->messageManager->getMessages(true));
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

}